### PR TITLE
Comment string change

### PR DESCRIPTION
**Pull request by ajoros**
Changed two comment lines from "string" to "list" to accurately reflect what input type is needed

### CODE REVIEW

**Comment by ghost** [comment]
cool thanks!

**Comment by ajoros** [comment]
No problem, there are some more I found but I'll merge them tomorrow when I get time.

**Comment by ghost** [comment]
awesome, any help is much appreciated.

**Comment by ajoros** [comment]
No problem, this package is awesome! Glad to help

**Pull request merged**
